name: dl-st
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - scipy
    - scikit-learn
    - scikit-image
    - pip:
        - tensorflow==1.2.0
